CoastalME (Coastal Modelling Environment): hermite_cubic.cpp File Reference
hermite_cubic.cpp File Reference
Some routines from the hermite_cubic library.
#include <iostream>
#include "cme.h"
#include "hermite_cubic.h"
Functions
void r8vec_bracket3 (int const n, double const *t, double const tval, int *left)
void hermite_cubic_value (double const x1, double const f1, double const d1, double const x2, double const f2, double const d2, int const n, double const *x, double *f, double *d, double *s, double *t)
void hermite_cubic_spline_value (int const nn, double *const xn, double *const fn, double *const dn, int const n, double *const x, double *f, double *d, double *s, double *t)
Detailed Description
Some routines from the hermite_cubic library.
TODO A more detailed description of these routines.
Author
John Burkardt
Modified by David Favis-Mortlock and Andres Payo
Date
2023
Copyright
GNU Lesser General Public License
Definition in file hermite_cubic.cpp.
Function Documentation
hermite_cubic_spline_value()
void hermite_cubic_spline_value (int const nn, double *const xn, double *const fn, double *const dn, int const n, double *const x, double * f, double * d, double * s, double * t)
Definition at line 354 of file hermite_cubic.cpp.
Referenced by CSimulation::bCreateErosionPotentialLookUp().
hermite_cubic_value()
void hermite_cubic_value (double const x1, double const f1, double const d1, double const x2, double const f2, double const d2, int const n, double const * x, double * f, double * d, double * s, double * t)
Definition at line 277 of file hermite_cubic.cpp.
Referenced by hermite_cubic_spline_value().
r8vec_bracket3()
void r8vec_bracket3 (int const n, double const * t, double const tval, int * left)
Definition at line 95 of file hermite_cubic.cpp.
Referenced by hermite_cubic_spline_value().