CoastalME (Coastal Modelling Environment): CGeomCoastPolygon Class Reference
CGeomCoastPolygon Class Reference
Geometry class used for coast polygon objects.
#include <coast_polygon.h>
Inherits CA2DShape.
Public Member Functions
CGeomCoastPolygon (int const, int const, int const, int const, int const, vector< CGeom2DPoint > const *, int const, int const, CGeom2DIPoint const *, CGeom2DIPoint const *, int const)
Constructor with 8 parameters.
~CGeomCoastPolygon (void)
void SetDownCoastThisIter (bool const)
bool bDownCoastThisIter (void) const
int nGetGlobalID (void) const
int nGetCoastID (void) const
int nGetNodeCoastPoint (void) const
CGeom2DIPoint * pPtiGetNode (void)
CGeom2DIPoint * pPtiGetAntiNode (void)
void SetNumCellsInPolygon (int const)
int nGetNumCellsinPolygon (void) const
int nGetUpCoastProfile (void) const
int nGetDownCoastProfile (void) const
CGeom2DPoint * pPtGetBoundaryPoint (int const)
int nGetBoundarySize (void) const
int nGetUpCoastProfileNumPointsUsed (void) const
int nGetDownCoastProfileNumPointsUsed (void) const
void SetSeawaterVolume (const double)
double dGetSeawaterVolume (void) const
void AddPotentialErosion (double const)
Adds in potential erosion of unconsolidated sediment (all size classes) on this polygon (m_dPotentialErosionAllUncons is <= 0)
double dGetPotentialErosion (void) const
Returns this timestep's total change in depth of unconsolidated sediment (all size classes) on this polygon (m_dPotentialErosionAllUncons <= 0)
void SetErosionUnconsFine (double const)
Sets a value (must be < 0) for this timestep's erosion of fine unconsolidated sediment on this polygon.
double dGetErosionUnconsFine (void) const
Returns this timestep's erosion (a value < 0) of fine unconsolidated sediment on this polygon.
void SetErosionUnconsSand (double const)
Sets a value (must be < 0) for this timestep's erosion of sand-sized unconsolidated sediment on this polygon.
double dGetErosionUnconsSand (void) const
Returns this timestep's erosion (a value < 0) of sand-sized unconsolidated sediment on this polygon.
void SetErosionUnconsCoarse (double const)
Sets a value (must be < 0) for this timestep's erosion of coarse unconsolidated sediment on this polygon.
double dGetErosionUnconsCoarse (void) const
Returns this timestep's erosion (a value < 0) of coarse unconsolidated sediment on this polygon.
double dGetErosionAllUncons (void) const
Returns this timestep's total (all size classes) eroson of unconsolidated sediment on this polygon, as a -ve depth in m.
void SetZeroDepositionUnconsFine (void)
Re-initializes this timestep's eposition of unconsolidated fine sediment on this polygon.
double dGetDepositionUnconsFine (void) const
Returns this timestep's deposition of fine unconsolidated sediment on this polygon, as a +ve depth in m.
void SetZeroDepositionUnconsSand (void)
Re-initializes this timestep's deposition of unconsolidated sand sediment on this polygon.
void AddDepositionUnconsSand (double const)
Adds a depth (in m) of sand-sized unconsolidated sediment to this timestep's deposition of unconsolidated coarse sediment on this polygon.
double dGetDepositionUnconsSand (void) const
Returns this timestep's deposition of sand-sized unconsolidated sediment on this polygon, as a +ve depth in m.
void SetZeroDepositionUnconsCoarse (void)
Re-initializes this timestep's deposition of unconsolidated coarse sediment on this polygon.
void AddDepositionUnconsCoarse (double const)
Adds a depth (in m) of coarse unconsolidated sediment to this timestep's deposition of unconsolidated coarse sediment on this polygon (+ve)
double dGetDepositionUnconsCoarse (void) const
Returns this timestep's deposition of coarse unconsolidated sediment on this polygon, as a +ve depth in m.
double dGetDepositionAllUncons (void) const
Returns this timestep's total (all size classes) deposition of unconsolidated sediment on this polygon, as a +ve depth in m.
void SetUpCoastAdjacentPolygons (vector< int > const *)
int nGetUpCoastAdjacentPolygon (int const) const
int nGetNumUpCoastAdjacentPolygons (void) const
void SetDownCoastAdjacentPolygons (vector< int > const *)
int nGetDownCoastAdjacentPolygon (int const) const
int nGetNumDownCoastAdjacentPolygons (void) const
void SetUpCoastAdjacentPolygonBoundaryShares (vector< double > const *)
double dGetUpCoastAdjacentPolygonBoundaryShare (int const) const
void SetDownCoastAdjacentPolygonBoundaryShares (vector< double > const *)
double dGetDownCoastAdjacentPolygonBoundaryShare (int const) const
int nGetPointInPolygonSearchStartPoint (void) const
void SetAvgUnconsD50 (double const)
double dGetAvgUnconsD50 (void) const
void Display (void) override
void AddCircularity (int const)
vector< int > VnGetCircularities (void)
void AddCliffCollapseErosionFine (double const)
double dGetCliffCollapseErosionFine (void) const
void AddCliffCollapseErosionSand (double const)
double dGetCliffCollapseErosionSand (void) const
void AddCliffCollapseErosionCoarse (double const)
double dGetCliffCollapseErosionCoarse (void) const
void AddCliffCollapseUnconsSandDeposition (double const)
double dGetCliffCollapseUnconsSandDeposition (void) const
void AddCliffCollapseUnconsCoarseDeposition (double const)
double dGetCliffCollapseUnconsCoarseDeposition (void) const
void AddUnconsSandFromShorePlatform (double const)
double dGetUnconsSandFromShorePlatform (void) const
void AddUnconsCoarseFromShorePlatform (double const)
double dGetUnconsCoarseFromShorePlatform (void) const
void SetStoredUnconsFine (double const)
double dGetStoredUnconsFine (void) const
void SetStoredUnconsSand (double const)
double dGetStoredUnconsSand (void) const
void SetStoredUnconsCoarse (double const)
double dGetStoredUnconsCoarse (void) const
Public Member Functions inherited from CA2DShape
CA2DShape (void)
Constructor.
virtual ~CA2DShape (void)
Destructor.
CGeom2DPoint & operator[] (int const)
Operator [] to return one point of this 2D shape.
void Clear (void)
Clears this 2D shape.
void Resize (int const)
Resizes the vector which represents this 2D shape.
int nGetSize (void) const
void Append (CGeom2DPoint const *)
Appends a point to this 2D shape.
void Append (double const, double const)
Appends a point to this 2D shape.
void AppendIfNotAlready (double const, double const)
Appends a point to this 2D shape only if it isn't already in the shape vector.
CGeom2DPoint * pPtBack (void)
Returns the last element of this 2D shape.
vector< CGeom2DPoint > * pPtVGetPoints (void)
Returns the address of the vector which represents this 2D shape.
CGeom2DPoint PtGetCentroid (void)
Computes the centroid of this 2D polygon (which may be outside, if this is a concave polygon). From http://stackoverflow.com/questions/2792443/finding-the-centroid-of-a-polygon.
void Reverse (void)
Reverses the sequence of points in the vector which represents this 2D polygon.
virtual void Display ()=0
Private Attributes
bool m_bDownCoastThisIter
int m_nGlobalID
int m_nCoastID
int m_nCoastNode
int m_nProfileUpCoast
int m_nProfileDownCoast
int m_nProfileUpCoastNumPointsUsed
int m_nProfileDownCoastNumPointsUsed
int m_nNumCells
int m_nPointInPolygonSearchStartPoint
double m_dAvgUnconsD50
double m_dSeawaterVolume
double m_dPotentialErosionAllUncons
double m_dErosionUnconsFine
double m_dErosionUnconsSand
double m_dErosionUnconsCoarse
double m_dDepositionUnconsFine
double m_dDepositionUnconsSand
double m_dDepositionUnconsCoarse
double m_dCliffCollapseErosionFine
double m_dCliffCollapseErosionSand
double m_dCliffCollapseErosionCoarse
double m_dCliffCollapseTalusSand
double m_dCliffCollapseTalusCoarse
double m_dSandFromPlatformErosion
double m_dCoarseFromPlatformErosion
double m_dStoredUnconsFine
double m_dStoredUnconsSand
double m_dStoredUnconsCoarse
CGeom2DIPoint m_PtiNode
CGeom2DIPoint m_PtiAntinode
vector< int > m_VnUpCoastAdjacentPolygon
vector< int > m_VnDownCoastAdjacentPolygon
vector< int > m_VnCircularityWith
vector< double > m_VdUpCoastAdjacentPolygonBoundaryShare
vector< double > m_VdDownCoastAdjacentPolygonBoundaryShare
Additional Inherited Members
Protected Attributes inherited from CA2DShape
vector< CGeom2DPoint > m_VPoints
The points which comprise the 2D shape.
Detailed Description
Geometry class used for coast polygon objects.
TODO This is a more detailed description of the CRWCoast class.
Author
David Favis-Mortlock
Andres Payo
Date
2023
Copyright
GNU General Public License
Definition at line 31 of file coast_polygon.h.
Constructor & Destructor Documentation
CGeomCoastPolygon()
CGeomCoastPolygon::CGeomCoastPolygon (int const nGlobalID, int const nCoastID, int const nNode, int const nProfileUpCoast, int const nProfileDownCoast, vector< CGeom2DPoint > const * pVIn, int const nLastPointUpCoast, int const nLastPointDownCoast, CGeom2DIPoint const * PtiNode, CGeom2DIPoint const * PtiAntinode, int const nPointInPolygonStartPoint)
Constructor with 8 parameters.
Definition at line 32 of file coast_polygon.cpp.
~CGeomCoastPolygon()
CGeomCoastPolygon::~CGeomCoastPolygon (void)
Definition at line 70 of file coast_polygon.cpp.
Member Function Documentation
AddCircularity()
void CGeomCoastPolygon::AddCircularity (int const nPoly)
Definition at line 376 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
AddCliffCollapseErosionCoarse()
void CGeomCoastPolygon::AddCliffCollapseErosionCoarse (double const dDepth)
Definition at line 406 of file coast_polygon.cpp.
Referenced by CSimulation::nDoCliffCollapse().
AddCliffCollapseErosionFine()
void CGeomCoastPolygon::AddCliffCollapseErosionFine (double const dDepth)
Definition at line 386 of file coast_polygon.cpp.
Referenced by CSimulation::nDoCliffCollapse().
AddCliffCollapseErosionSand()
void CGeomCoastPolygon::AddCliffCollapseErosionSand (double const dDepth)
Definition at line 396 of file coast_polygon.cpp.
Referenced by CSimulation::nDoCliffCollapse().
AddCliffCollapseUnconsCoarseDeposition()
void CGeomCoastPolygon::AddCliffCollapseUnconsCoarseDeposition (double const dDepth)
Definition at line 426 of file coast_polygon.cpp.
Referenced by CSimulation::nDoCliffCollapseDeposition().
AddCliffCollapseUnconsSandDeposition()
void CGeomCoastPolygon::AddCliffCollapseUnconsSandDeposition (double const dDepth)
Definition at line 416 of file coast_polygon.cpp.
Referenced by CSimulation::nDoCliffCollapseDeposition().
AddDepositionUnconsCoarse()
void CGeomCoastPolygon::AddDepositionUnconsCoarse (double const dDepth)
Adds a depth (in m) of coarse unconsolidated sediment to this timestep's deposition of unconsolidated coarse sediment on this polygon (+ve)
Definition at line 280 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
AddDepositionUnconsSand()
void CGeomCoastPolygon::AddDepositionUnconsSand (double const dDepth)
Adds a depth (in m) of sand-sized unconsolidated sediment to this timestep's deposition of unconsolidated coarse sediment on this polygon.
Definition at line 262 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
AddPotentialErosion()
void CGeomCoastPolygon::AddPotentialErosion (double const dDepth)
Adds in potential erosion of unconsolidated sediment (all size classes) on this polygon (m_dPotentialErosionAllUncons is <= 0)
Definition at line 190 of file coast_polygon.cpp.
Referenced by CSimulation::DoAllPotentialBeachErosion().
AddUnconsCoarseFromShorePlatform()
void CGeomCoastPolygon::AddUnconsCoarseFromShorePlatform (double const dDepth)
Definition at line 446 of file coast_polygon.cpp.
AddUnconsSandFromShorePlatform()
void CGeomCoastPolygon::AddUnconsSandFromShorePlatform (double const dDepth)
Definition at line 436 of file coast_polygon.cpp.
bDownCoastThisIter()
bool CGeomCoastPolygon::bDownCoastThisIter (void) const
Definition at line 91 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
dGetAvgUnconsD50()
double CGeomCoastPolygon::dGetAvgUnconsD50 (void) const
Definition at line 362 of file coast_polygon.cpp.
Referenced by CSimulation::DoAllPotentialBeachErosion().
dGetCliffCollapseErosionCoarse()
double CGeomCoastPolygon::dGetCliffCollapseErosionCoarse (void) const
Definition at line 411 of file coast_polygon.cpp.
dGetCliffCollapseErosionFine()
double CGeomCoastPolygon::dGetCliffCollapseErosionFine (void) const
Definition at line 391 of file coast_polygon.cpp.
dGetCliffCollapseErosionSand()
double CGeomCoastPolygon::dGetCliffCollapseErosionSand (void) const
Definition at line 401 of file coast_polygon.cpp.
dGetCliffCollapseUnconsCoarseDeposition()
double CGeomCoastPolygon::dGetCliffCollapseUnconsCoarseDeposition (void) const
Definition at line 431 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons().
dGetCliffCollapseUnconsSandDeposition()
double CGeomCoastPolygon::dGetCliffCollapseUnconsSandDeposition (void) const
Definition at line 421 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons().
dGetDepositionAllUncons()
double CGeomCoastPolygon::dGetDepositionAllUncons (void) const
Returns this timestep's total (all size classes) deposition of unconsolidated sediment on this polygon, as a +ve depth in m.
Definition at line 292 of file coast_polygon.cpp.
Referenced by CSimulation::bWriteVectorGISFile().
dGetDepositionUnconsCoarse()
double CGeomCoastPolygon::dGetDepositionUnconsCoarse (void) const
Returns this timestep's deposition of coarse unconsolidated sediment on this polygon, as a +ve depth in m.
Definition at line 286 of file coast_polygon.cpp.
Referenced by CSimulation::bWriteVectorGISFile().
dGetDepositionUnconsFine()
double CGeomCoastPolygon::dGetDepositionUnconsFine (void) const
Returns this timestep's deposition of fine unconsolidated sediment on this polygon, as a +ve depth in m.
Definition at line 250 of file coast_polygon.cpp.
Referenced by CSimulation::bWriteVectorGISFile().
dGetDepositionUnconsSand()
double CGeomCoastPolygon::dGetDepositionUnconsSand (void) const
Returns this timestep's deposition of sand-sized unconsolidated sediment on this polygon, as a +ve depth in m.
Definition at line 268 of file coast_polygon.cpp.
Referenced by CSimulation::bWriteVectorGISFile().
dGetDownCoastAdjacentPolygonBoundaryShare()
double CGeomCoastPolygon::dGetDownCoastAdjacentPolygonBoundaryShare (int const nIndex) const
Definition at line 346 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
dGetErosionAllUncons()
double CGeomCoastPolygon::dGetErosionAllUncons (void) const
Returns this timestep's total (all size classes) eroson of unconsolidated sediment on this polygon, as a -ve depth in m.
Definition at line 238 of file coast_polygon.cpp.
dGetErosionUnconsCoarse()
double CGeomCoastPolygon::dGetErosionUnconsCoarse (void) const
Returns this timestep's erosion (a value < 0) of coarse unconsolidated sediment on this polygon.
Definition at line 232 of file coast_polygon.cpp.
Referenced by CSimulation::WritePolygonUnconsErosion().
dGetErosionUnconsFine()
double CGeomCoastPolygon::dGetErosionUnconsFine (void) const
Returns this timestep's erosion (a value < 0) of fine unconsolidated sediment on this polygon.
Definition at line 208 of file coast_polygon.cpp.
Referenced by CSimulation::WritePolygonUnconsErosion().
dGetErosionUnconsSand()
double CGeomCoastPolygon::dGetErosionUnconsSand (void) const
Returns this timestep's erosion (a value < 0) of sand-sized unconsolidated sediment on this polygon.
Definition at line 220 of file coast_polygon.cpp.
Referenced by CSimulation::WritePolygonUnconsErosion().
dGetPotentialErosion()
double CGeomCoastPolygon::dGetPotentialErosion (void) const
Returns this timestep's total change in depth of unconsolidated sediment (all size classes) on this polygon (m_dPotentialErosionAllUncons <= 0)
Definition at line 196 of file coast_polygon.cpp.
dGetSeawaterVolume()
double CGeomCoastPolygon::dGetSeawaterVolume (void) const
Definition at line 184 of file coast_polygon.cpp.
dGetStoredUnconsCoarse()
double CGeomCoastPolygon::dGetStoredUnconsCoarse (void) const
Definition at line 481 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons().
dGetStoredUnconsFine()
double CGeomCoastPolygon::dGetStoredUnconsFine (void) const
Definition at line 461 of file coast_polygon.cpp.
dGetStoredUnconsSand()
double CGeomCoastPolygon::dGetStoredUnconsSand (void) const
Definition at line 471 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons().
dGetUnconsCoarseFromShorePlatform()
double CGeomCoastPolygon::dGetUnconsCoarseFromShorePlatform (void) const
Definition at line 451 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons().
dGetUnconsSandFromShorePlatform()
double CGeomCoastPolygon::dGetUnconsSandFromShorePlatform (void) const
Definition at line 441 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons().
dGetUpCoastAdjacentPolygonBoundaryShare()
double CGeomCoastPolygon::dGetUpCoastAdjacentPolygonBoundaryShare (int const nIndex) const
Definition at line 335 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
Display()
void CGeomCoastPolygon::Display (void) override virtual
Implements CA2DShape.
Definition at line 367 of file coast_polygon.cpp.
nGetBoundarySize()
int CGeomCoastPolygon::nGetBoundarySize (void) const
Definition at line 164 of file coast_polygon.cpp.
Referenced by CSimulation::bWriteVectorGISFile(), and CSimulation::MarkPolygonCells().
nGetCoastID()
int CGeomCoastPolygon::nGetCoastID (void) const
Definition at line 102 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
nGetDownCoastAdjacentPolygon()
int CGeomCoastPolygon::nGetDownCoastAdjacentPolygon (int const nIndex) const
Definition at line 319 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
nGetDownCoastProfile()
int CGeomCoastPolygon::nGetDownCoastProfile (void) const
Definition at line 143 of file coast_polygon.cpp.
Referenced by CSimulation::DoAllPotentialBeachErosion(), CSimulation::nDoPolygonSharedBoundaries(), CSimulation::nDoUnconsDepositionOnPolygon(), and CSimulation::nDoUnconsErosionOnPolygon().
nGetDownCoastProfileNumPointsUsed()
int CGeomCoastPolygon::nGetDownCoastProfileNumPointsUsed (void) const
Definition at line 174 of file coast_polygon.cpp.
Referenced by CSimulation::nDoPolygonSharedBoundaries().
nGetGlobalID()
int CGeomCoastPolygon::nGetGlobalID (void) const
Definition at line 97 of file coast_polygon.cpp.
Referenced by CSimulation::CalcD50AndFillWaveCalcHoles(), and CSimulation::MarkPolygonCells().
nGetNodeCoastPoint()
int CGeomCoastPolygon::nGetNodeCoastPoint (void) const
Definition at line 112 of file coast_polygon.cpp.
Referenced by CSimulation::bWriteVectorGISFile().
nGetNumCellsinPolygon()
int CGeomCoastPolygon::nGetNumCellsinPolygon (void) const
Definition at line 133 of file coast_polygon.cpp.
nGetNumDownCoastAdjacentPolygons()
int CGeomCoastPolygon::nGetNumDownCoastAdjacentPolygons (void) const
Definition at line 325 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
nGetNumUpCoastAdjacentPolygons()
int CGeomCoastPolygon::nGetNumUpCoastAdjacentPolygons (void) const
Definition at line 308 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
nGetPointInPolygonSearchStartPoint()
int CGeomCoastPolygon::nGetPointInPolygonSearchStartPoint (void) const
Definition at line 352 of file coast_polygon.cpp.
Referenced by CSimulation::MarkPolygonCells().
nGetUpCoastAdjacentPolygon()
int CGeomCoastPolygon::nGetUpCoastAdjacentPolygon (int const nIndex) const
Definition at line 302 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
nGetUpCoastProfile()
int CGeomCoastPolygon::nGetUpCoastProfile (void) const
Definition at line 138 of file coast_polygon.cpp.
Referenced by CSimulation::DoAllPotentialBeachErosion(), CSimulation::nDoPolygonSharedBoundaries(), CSimulation::nDoUnconsDepositionOnPolygon(), and CSimulation::nDoUnconsErosionOnPolygon().
nGetUpCoastProfileNumPointsUsed()
int CGeomCoastPolygon::nGetUpCoastProfileNumPointsUsed (void) const
Definition at line 169 of file coast_polygon.cpp.
Referenced by CSimulation::nDoPolygonSharedBoundaries().
pPtGetBoundaryPoint()
CGeom2DPoint * CGeomCoastPolygon::pPtGetBoundaryPoint (int const nPoint)
Definition at line 158 of file coast_polygon.cpp.
Referenced by CSimulation::bWriteVectorGISFile(), and CSimulation::MarkPolygonCells().
pPtiGetAntiNode()
CGeom2DIPoint * CGeomCoastPolygon::pPtiGetAntiNode (void)
Definition at line 123 of file coast_polygon.cpp.
Referenced by CSimulation::nDoPolygonSharedBoundaries().
pPtiGetNode()
CGeom2DIPoint * CGeomCoastPolygon::pPtiGetNode (void)
Definition at line 117 of file coast_polygon.cpp.
Referenced by CSimulation::nDoPolygonSharedBoundaries().
SetAvgUnconsD50()
void CGeomCoastPolygon::SetAvgUnconsD50 (double const dD50)
Definition at line 357 of file coast_polygon.cpp.
Referenced by CSimulation::CalcD50AndFillWaveCalcHoles().
SetDownCoastAdjacentPolygonBoundaryShares()
void CGeomCoastPolygon::SetDownCoastAdjacentPolygonBoundaryShares (vector< double > const * pdVShares)
Definition at line 341 of file coast_polygon.cpp.
Referenced by CSimulation::nDoPolygonSharedBoundaries().
SetDownCoastAdjacentPolygons()
void CGeomCoastPolygon::SetDownCoastAdjacentPolygons (vector< int > const * pnVPolygons)
Definition at line 314 of file coast_polygon.cpp.
Referenced by CSimulation::nDoPolygonSharedBoundaries().
SetDownCoastThisIter()
void CGeomCoastPolygon::SetDownCoastThisIter (bool const bFlag)
Definition at line 86 of file coast_polygon.cpp.
Referenced by CSimulation::DoAllPotentialBeachErosion().
SetErosionUnconsCoarse()
void CGeomCoastPolygon::SetErosionUnconsCoarse (double const dDepth)
Sets a value (must be < 0) for this timestep's erosion of coarse unconsolidated sediment on this polygon.
Definition at line 226 of file coast_polygon.cpp.
SetErosionUnconsFine()
void CGeomCoastPolygon::SetErosionUnconsFine (double const dDepth)
Sets a value (must be < 0) for this timestep's erosion of fine unconsolidated sediment on this polygon.
Definition at line 202 of file coast_polygon.cpp.
SetErosionUnconsSand()
void CGeomCoastPolygon::SetErosionUnconsSand (double const dDepth)
Sets a value (must be < 0) for this timestep's erosion of sand-sized unconsolidated sediment on this polygon.
Definition at line 214 of file coast_polygon.cpp.
SetNumCellsInPolygon()
void CGeomCoastPolygon::SetNumCellsInPolygon (int const nCells)
Definition at line 128 of file coast_polygon.cpp.
Referenced by CSimulation::MarkPolygonCells().
SetSeawaterVolume()
void CGeomCoastPolygon::SetSeawaterVolume (const double dDepth)
Definition at line 179 of file coast_polygon.cpp.
Referenced by CSimulation::MarkPolygonCells().
SetStoredUnconsCoarse()
void CGeomCoastPolygon::SetStoredUnconsCoarse (double const dDepth)
Definition at line 476 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons(), and CSimulation::MarkPolygonCells().
SetStoredUnconsFine()
void CGeomCoastPolygon::SetStoredUnconsFine (double const dDepth)
Definition at line 456 of file coast_polygon.cpp.
Referenced by CSimulation::MarkPolygonCells().
SetStoredUnconsSand()
void CGeomCoastPolygon::SetStoredUnconsSand (double const dDepth)
Definition at line 466 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons(), and CSimulation::MarkPolygonCells().
SetUpCoastAdjacentPolygonBoundaryShares()
void CGeomCoastPolygon::SetUpCoastAdjacentPolygonBoundaryShares (vector< double > const * pdVShares)
Definition at line 330 of file coast_polygon.cpp.
Referenced by CSimulation::nDoPolygonSharedBoundaries().
SetUpCoastAdjacentPolygons()
void CGeomCoastPolygon::SetUpCoastAdjacentPolygons (vector< int > const * pnVPolygons)
Definition at line 297 of file coast_polygon.cpp.
Referenced by CSimulation::nDoPolygonSharedBoundaries().
SetZeroDepositionUnconsCoarse()
void CGeomCoastPolygon::SetZeroDepositionUnconsCoarse (void)
Re-initializes this timestep's deposition of unconsolidated coarse sediment on this polygon.
Definition at line 274 of file coast_polygon.cpp.
SetZeroDepositionUnconsFine()
void CGeomCoastPolygon::SetZeroDepositionUnconsFine (void)
Re-initializes this timestep's eposition of unconsolidated fine sediment on this polygon.
Definition at line 244 of file coast_polygon.cpp.
SetZeroDepositionUnconsSand()
void CGeomCoastPolygon::SetZeroDepositionUnconsSand (void)
Re-initializes this timestep's deposition of unconsolidated sand sediment on this polygon.
Definition at line 256 of file coast_polygon.cpp.
VnGetCircularities()
vector< int > CGeomCoastPolygon::VnGetCircularities (void)
Definition at line 381 of file coast_polygon.cpp.
Referenced by CSimulation::WritePolygonSortedSequence().
Field Documentation
m_bDownCoastThisIter
bool CGeomCoastPolygon::m_bDownCoastThisIter private
Definition at line 36 of file coast_polygon.h.
Referenced by bDownCoastThisIter(), and SetDownCoastThisIter().
m_dAvgUnconsD50
double CGeomCoastPolygon::m_dAvgUnconsD50 private
Definition at line 51 of file coast_polygon.h.
Referenced by dGetAvgUnconsD50(), and SetAvgUnconsD50().
m_dCliffCollapseErosionCoarse
double CGeomCoastPolygon::m_dCliffCollapseErosionCoarse private
Definition at line 62 of file coast_polygon.h.
Referenced by AddCliffCollapseErosionCoarse(), and dGetCliffCollapseErosionCoarse().
m_dCliffCollapseErosionFine
double CGeomCoastPolygon::m_dCliffCollapseErosionFine private
Definition at line 60 of file coast_polygon.h.
Referenced by AddCliffCollapseErosionFine(), and dGetCliffCollapseErosionFine().
m_dCliffCollapseErosionSand
double CGeomCoastPolygon::m_dCliffCollapseErosionSand private
Definition at line 61 of file coast_polygon.h.
Referenced by AddCliffCollapseErosionSand(), and dGetCliffCollapseErosionSand().
m_dCliffCollapseTalusCoarse
double CGeomCoastPolygon::m_dCliffCollapseTalusCoarse private
Definition at line 64 of file coast_polygon.h.
Referenced by AddCliffCollapseUnconsCoarseDeposition(), and dGetCliffCollapseUnconsCoarseDeposition().
m_dCliffCollapseTalusSand
double CGeomCoastPolygon::m_dCliffCollapseTalusSand private
Definition at line 63 of file coast_polygon.h.
Referenced by AddCliffCollapseUnconsSandDeposition(), and dGetCliffCollapseUnconsSandDeposition().
m_dCoarseFromPlatformErosion
double CGeomCoastPolygon::m_dCoarseFromPlatformErosion private
Definition at line 66 of file coast_polygon.h.
Referenced by AddUnconsCoarseFromShorePlatform(), and dGetUnconsCoarseFromShorePlatform().
m_dDepositionUnconsCoarse
double CGeomCoastPolygon::m_dDepositionUnconsCoarse private
Definition at line 59 of file coast_polygon.h.
Referenced by AddDepositionUnconsCoarse(), dGetDepositionAllUncons(), dGetDepositionUnconsCoarse(), and SetZeroDepositionUnconsCoarse().
m_dDepositionUnconsFine
double CGeomCoastPolygon::m_dDepositionUnconsFine private
Definition at line 57 of file coast_polygon.h.
Referenced by dGetDepositionAllUncons(), dGetDepositionUnconsFine(), and SetZeroDepositionUnconsFine().
m_dDepositionUnconsSand
double CGeomCoastPolygon::m_dDepositionUnconsSand private
Definition at line 58 of file coast_polygon.h.
Referenced by AddDepositionUnconsSand(), dGetDepositionAllUncons(), dGetDepositionUnconsSand(), and SetZeroDepositionUnconsSand().
m_dErosionUnconsCoarse
double CGeomCoastPolygon::m_dErosionUnconsCoarse private
Definition at line 56 of file coast_polygon.h.
Referenced by dGetErosionAllUncons(), dGetErosionUnconsCoarse(), and SetErosionUnconsCoarse().
m_dErosionUnconsFine
double CGeomCoastPolygon::m_dErosionUnconsFine private
Definition at line 54 of file coast_polygon.h.
Referenced by dGetErosionAllUncons(), dGetErosionUnconsFine(), and SetErosionUnconsFine().
m_dErosionUnconsSand
double CGeomCoastPolygon::m_dErosionUnconsSand private
Definition at line 55 of file coast_polygon.h.
Referenced by dGetErosionAllUncons(), dGetErosionUnconsSand(), and SetErosionUnconsSand().
m_dPotentialErosionAllUncons
double CGeomCoastPolygon::m_dPotentialErosionAllUncons private
Definition at line 53 of file coast_polygon.h.
Referenced by AddPotentialErosion(), and dGetPotentialErosion().
m_dSandFromPlatformErosion
double CGeomCoastPolygon::m_dSandFromPlatformErosion private
Definition at line 65 of file coast_polygon.h.
Referenced by AddUnconsSandFromShorePlatform(), and dGetUnconsSandFromShorePlatform().
m_dSeawaterVolume
double CGeomCoastPolygon::m_dSeawaterVolume private
Definition at line 52 of file coast_polygon.h.
Referenced by dGetSeawaterVolume(), and SetSeawaterVolume().
m_dStoredUnconsCoarse
double CGeomCoastPolygon::m_dStoredUnconsCoarse private
Definition at line 69 of file coast_polygon.h.
Referenced by dGetStoredUnconsCoarse(), and SetStoredUnconsCoarse().
m_dStoredUnconsFine
double CGeomCoastPolygon::m_dStoredUnconsFine private
Definition at line 67 of file coast_polygon.h.
Referenced by dGetStoredUnconsFine(), and SetStoredUnconsFine().
m_dStoredUnconsSand
double CGeomCoastPolygon::m_dStoredUnconsSand private
Definition at line 68 of file coast_polygon.h.
Referenced by dGetStoredUnconsSand(), and SetStoredUnconsSand().
m_nCoastID
int CGeomCoastPolygon::m_nCoastID private
Definition at line 40 of file coast_polygon.h.
Referenced by nGetCoastID().
m_nCoastNode
int CGeomCoastPolygon::m_nCoastNode private
Definition at line 41 of file coast_polygon.h.
Referenced by nGetNodeCoastPoint().
m_nGlobalID
int CGeomCoastPolygon::m_nGlobalID private
Definition at line 39 of file coast_polygon.h.
Referenced by nGetGlobalID().
m_nNumCells
int CGeomCoastPolygon::m_nNumCells private
Definition at line 46 of file coast_polygon.h.
Referenced by nGetNumCellsinPolygon(), and SetNumCellsInPolygon().
m_nPointInPolygonSearchStartPoint
int CGeomCoastPolygon::m_nPointInPolygonSearchStartPoint private
Definition at line 47 of file coast_polygon.h.
Referenced by nGetPointInPolygonSearchStartPoint().
m_nProfileDownCoast
int CGeomCoastPolygon::m_nProfileDownCoast private
Definition at line 43 of file coast_polygon.h.
Referenced by nGetDownCoastProfile().
m_nProfileDownCoastNumPointsUsed
int CGeomCoastPolygon::m_nProfileDownCoastNumPointsUsed private
Definition at line 45 of file coast_polygon.h.
Referenced by nGetDownCoastProfileNumPointsUsed().
m_nProfileUpCoast
int CGeomCoastPolygon::m_nProfileUpCoast private
Definition at line 42 of file coast_polygon.h.
Referenced by nGetUpCoastProfile().
m_nProfileUpCoastNumPointsUsed
int CGeomCoastPolygon::m_nProfileUpCoastNumPointsUsed private
Definition at line 44 of file coast_polygon.h.
Referenced by nGetUpCoastProfileNumPointsUsed().
m_PtiAntinode
CGeom2DIPoint CGeomCoastPolygon::m_PtiAntinode private
Definition at line 73 of file coast_polygon.h.
Referenced by pPtiGetAntiNode().
m_PtiNode
CGeom2DIPoint CGeomCoastPolygon::m_PtiNode private
Definition at line 72 of file coast_polygon.h.
Referenced by pPtiGetNode().
m_VdDownCoastAdjacentPolygonBoundaryShare
vector<double> CGeomCoastPolygon::m_VdDownCoastAdjacentPolygonBoundaryShare private
Definition at line 82 of file coast_polygon.h.
Referenced by dGetDownCoastAdjacentPolygonBoundaryShare(), and SetDownCoastAdjacentPolygonBoundaryShares().
m_VdUpCoastAdjacentPolygonBoundaryShare
vector<double> CGeomCoastPolygon::m_VdUpCoastAdjacentPolygonBoundaryShare private
Definition at line 81 of file coast_polygon.h.
Referenced by dGetUpCoastAdjacentPolygonBoundaryShare(), and SetUpCoastAdjacentPolygonBoundaryShares().
m_VnCircularityWith
vector<int> CGeomCoastPolygon::m_VnCircularityWith private
Definition at line 78 of file coast_polygon.h.
Referenced by AddCircularity(), and VnGetCircularities().
m_VnDownCoastAdjacentPolygon
vector<int> CGeomCoastPolygon::m_VnDownCoastAdjacentPolygon private
Definition at line 77 of file coast_polygon.h.
Referenced by nGetDownCoastAdjacentPolygon(), nGetNumDownCoastAdjacentPolygons(), and SetDownCoastAdjacentPolygons().
m_VnUpCoastAdjacentPolygon
vector<int> CGeomCoastPolygon::m_VnUpCoastAdjacentPolygon private
Definition at line 76 of file coast_polygon.h.
Referenced by nGetNumUpCoastAdjacentPolygons(), nGetUpCoastAdjacentPolygon(), and SetUpCoastAdjacentPolygons().
The documentation for this class was generated from the following files:
coast_polygon.h
coast_polygon.cpp