CoastalME (Coastal Modelling Environment): interpolate.cpp File Reference
interpolate.cpp File Reference
Linear interpolation routines.
#include <iostream>
#include <iomanip>
#include <vector>
#include "cme.h"
Functions
double dInterpolate (vector< double > VdXdata, vector< double > VdYdata, double dX, bool bExtrapolate)
double dInterpolate (vector< int > VnXdata, vector< double > VdYdata, int nX, bool bExtrapolate)
Detailed Description
Linear interpolation routines.
TODO A more detailed description of these routines.
Author
http://www.cplusplus.com/forum/general/216928/
Modified by David Favis-Mortlock and Andres Payo
Date
2023
Copyright
GNU Lesser General Public License
Definition in file interpolate.cpp.
Function Documentation
dInterpolate() [1/2]
double dInterpolate (vector< double > VdXdata, vector< double > VdYdata, double dX, bool bExtrapolate)
Definition at line 36 of file interpolate.cpp.
Referenced by CSimulation::dLookUpErosionPotential(), CSimulation::InterpolateWaveHeightToCoastPoints(), and CSimulation::WriteLookUpData().
dInterpolate() [2/2]
double dInterpolate (vector< int > VnXdata, vector< double > VdYdata, int nX, bool bExtrapolate)
Definition at line 72 of file interpolate.cpp.