CoastalME (Coastal Modelling Environment): CRWCellSediment Class Reference
CRWCellSediment Class Reference
Real-world class used to represent the sediment (either consolidated or unconsolidated) associated with a cell layer object.
#include <cell_sediment.h>
Public Member Functions
CRWCellSediment (void)
CRWCellSediment constructor, sets all internal values to zero.
CRWCellSediment (CRWCellSediment const &)
CRWCellSediment copy constructor.
CRWCellSediment & operator= (const CRWCellSediment &)
Sets one CRWCellSediment object equal to another.
void SetFineDepth (double const)
double dGetFineDepth (void) const
void AddFineDepth (double const)
void SetSandDepth (double const)
double dGetSandDepth (void) const
void AddSandDepth (double const)
void SetCoarseDepth (double const)
double dGetCoarseDepth (void) const
void AddCoarseDepth (double const)
void SetNotchFineLost (double const)
void IncrNotchFineLost (double const)
double dGetNotchFineLost (void) const
void SetNotchSandLost (double const)
void IncrNotchSandLost (double const)
double dGetNotchSandLost (void) const
void SetNotchCoarseLost (double const)
void IncrNotchCoarseLost (double const)
double dGetNotchCoarseLost (void) const
void AddToTotSedimentInputDepth (double const)
Adds to the total (since the start of simulation) depth of sediment input, all size classes.
double dGetTotSedimentInputDepth (void) const
Returns the total (since the start of simulation) depth of sediment input, all size classes.
Detailed Description
Real-world class used to represent the sediment (either consolidated or unconsolidated) associated with a cell layer object.
TODO This is a more detailed description of the CRWCellSediment class.
Author
David Favis-Mortlock
Andres Payo
Date
2023
Copyright
GNU General Public License
Definition at line 30 of file cell_sediment.h.
Constructor & Destructor Documentation
CRWCellSediment() [1/2]
CRWCellSediment::CRWCellSediment (void)
CRWCellSediment constructor, sets all internal values to zero.
Definition at line 32 of file cell_sediment.cpp.
CRWCellSediment() [2/2]
CRWCellSediment::CRWCellSediment (CRWCellSediment const & OtherSediment)
CRWCellSediment copy constructor.
Definition at line 44 of file cell_sediment.cpp.
Member Function Documentation
AddCoarseDepth()
void CRWCellSediment::AddCoarseDepth (double const dSedDepthToAdd)
Definition at line 120 of file cell_sediment.cpp.
AddFineDepth()
void CRWCellSediment::AddFineDepth (double const dSedDepthToAdd)
Definition at line 83 of file cell_sediment.cpp.
AddSandDepth()
void CRWCellSediment::AddSandDepth (double const dSedDepthToAdd)
Definition at line 102 of file cell_sediment.cpp.
AddToTotSedimentInputDepth()
void CRWCellSediment::AddToTotSedimentInputDepth (double const dDepth)
Adds to the total (since the start of simulation) depth of sediment input, all size classes.
Definition at line 183 of file cell_sediment.cpp.
dGetCoarseDepth()
double CRWCellSediment::dGetCoarseDepth (void) const
Definition at line 114 of file cell_sediment.cpp.
Referenced by CGeomCell::CalcAllLayerElevsAndD50(), CRWCellLayer::dGetCoarseConsolidatedThickness(), CRWCellLayer::dGetCoarseUnconsolidatedThickness(), CRWCellLayer::dGetConsolidatedThickness(), CRWCellLayer::dGetTotalThickness(), and CRWCellLayer::dGetUnconsolidatedThickness().
dGetFineDepth()
double CRWCellSediment::dGetFineDepth (void) const
Definition at line 77 of file cell_sediment.cpp.
Referenced by CGeomCell::CalcAllLayerElevsAndD50(), CRWCellLayer::dGetConsolidatedThickness(), CRWCellLayer::dGetFineConsolidatedThickness(), CRWCellLayer::dGetFineUnconsolidatedThickness(), CRWCellLayer::dGetTotalThickness(), and CRWCellLayer::dGetUnconsolidatedThickness().
dGetNotchCoarseLost()
double CRWCellSediment::dGetNotchCoarseLost (void) const
Definition at line 177 of file cell_sediment.cpp.
Referenced by CRWCellLayer::dGetNotchConsolidatedLost(), CRWCellLayer::dGetNotchUnconsolidatedLost(), and CGeomCell::dGetTotConsCoarseThickConsiderNotch().
dGetNotchFineLost()
double CRWCellSediment::dGetNotchFineLost (void) const
Definition at line 139 of file cell_sediment.cpp.
Referenced by CRWCellLayer::dGetNotchConsolidatedLost(), CRWCellLayer::dGetNotchUnconsolidatedLost(), and CGeomCell::dGetTotConsFineThickConsiderNotch().
dGetNotchSandLost()
double CRWCellSediment::dGetNotchSandLost (void) const
Definition at line 158 of file cell_sediment.cpp.
Referenced by CRWCellLayer::dGetNotchConsolidatedLost(), CRWCellLayer::dGetNotchUnconsolidatedLost(), and CGeomCell::dGetTotConsSandThickConsiderNotch().
dGetSandDepth()
double CRWCellSediment::dGetSandDepth (void) const
Definition at line 96 of file cell_sediment.cpp.
Referenced by CGeomCell::CalcAllLayerElevsAndD50(), CRWCellLayer::dGetConsolidatedThickness(), CRWCellLayer::dGetSandConsolidatedThickness(), CRWCellLayer::dGetSandUnconsolidatedThickness(), CRWCellLayer::dGetTotalThickness(), and CRWCellLayer::dGetUnconsolidatedThickness().
dGetTotSedimentInputDepth()
double CRWCellSediment::dGetTotSedimentInputDepth (void) const
Returns the total (since the start of simulation) depth of sediment input, all size classes.
Definition at line 189 of file cell_sediment.cpp.
IncrNotchCoarseLost()
void CRWCellSediment::IncrNotchCoarseLost (double const dDepthIn)
Definition at line 170 of file cell_sediment.cpp.
IncrNotchFineLost()
void CRWCellSediment::IncrNotchFineLost (double const dDepthIn)
Definition at line 132 of file cell_sediment.cpp.
IncrNotchSandLost()
void CRWCellSediment::IncrNotchSandLost (double const dDepthIn)
Definition at line 151 of file cell_sediment.cpp.
operator=()
CRWCellSediment & CRWCellSediment::operator= (const CRWCellSediment & OtherSediment)
Sets one CRWCellSediment object equal to another.
Definition at line 56 of file cell_sediment.cpp.
SetCoarseDepth()
void CRWCellSediment::SetCoarseDepth (double const dNewSedDepth)
Definition at line 108 of file cell_sediment.cpp.
SetFineDepth()
void CRWCellSediment::SetFineDepth (double const dNewSedDepth)
Definition at line 71 of file cell_sediment.cpp.
SetNotchCoarseLost()
void CRWCellSediment::SetNotchCoarseLost (double const dDepthIn)
Definition at line 164 of file cell_sediment.cpp.
SetNotchFineLost()
void CRWCellSediment::SetNotchFineLost (double const dDepthIn)
Definition at line 126 of file cell_sediment.cpp.
SetNotchSandLost()
void CRWCellSediment::SetNotchSandLost (double const dDepthIn)
Definition at line 145 of file cell_sediment.cpp.
SetSandDepth()
void CRWCellSediment::SetSandDepth (double const dNewSedDepth)
Definition at line 89 of file cell_sediment.cpp.
The documentation for this class was generated from the following files:
cell_sediment.h
cell_sediment.cpp