CoastalME (Coastal Modelling Environment): CGeom2DPoint Class Reference
CGeom2DPoint Class Reference
Geometry class used to represent 2D point objects with floating-point co-ordinates.
#include <2d_point.h>
Public Member Functions
CGeom2DPoint (void)
Constructor with no parameters (the X and Y co-ordinates of the CGeom2DPoint object are set to zero)
CGeom2DPoint (double const, double const)
Constructor with two double parameters, for the X and Y co-ordinates of the CGeom2DPoint object.
double dGetX (void) const
Returns the CGeom2DPoint object's double X co-ordinate.
double dGetY (void) const
Returns the CGeom2DPoint object's double Y co-ordinate.
void SetX (double const)
The double parameter sets a value for the CGeom2DIPoint object's X co-ordinate.
void SetY (double const)
The double parameter sets a value for the CGeom2DIPoint object's Y co-ordinate.
void operator= (CGeom2DPoint *)
Sets one CGeom2DPoint object equal to another.
bool operator== (CGeom2DPoint *) const
Compares two CGeom2DPoint objects for equality.
bool operator== (CGeom2DPoint) const
Compares two CGeom2DPoint objects for equality.
bool operator!= (CGeom2DPoint *) const
Compares two CGeom2DPoint objects for inequality.
Private Attributes
double dX
The x co-ordinate.
double dY
The y co-ordinate.
Detailed Description
Geometry class used to represent 2D point objects with floating-point co-ordinates.
The CGeom2DPoint geometry class is used to represent 2D points where the x and y co-ordinates are floating-point values, e.g. points for which the x and y co-ordinates are in the external CRS (co-ordinate reference system)
Author
David Favis-Mortlock
Andres Payo
Date
2023
Copyright
GNU General Public License
Definition at line 29 of file 2d_point.h.
Constructor & Destructor Documentation
CGeom2DPoint() [1/2]
CGeom2DPoint::CGeom2DPoint (void)
Constructor with no parameters (the X and Y co-ordinates of the CGeom2DPoint object are set to zero)
Definition at line 28 of file 2d_point.cpp.
CGeom2DPoint() [2/2]
CGeom2DPoint::CGeom2DPoint (double const dNewX, double const dNewY)
Constructor with two double parameters, for the X and Y co-ordinates of the CGeom2DPoint object.
Definition at line 35 of file 2d_point.cpp.
Member Function Documentation
dGetX()
double CGeom2DPoint::dGetX (void) const
Returns the CGeom2DPoint object's double X co-ordinate.
Definition at line 42 of file 2d_point.cpp.
Referenced by CSimulation::bIsWithinPolygon(), CSimulation::bWriteVectorGISFile(), CSimulation::CalcCoastTangents(), CSimulation::CreateInterventionProfiles(), CSimulation::CreateNaturalCapeNormalProfiles(), CSimulation::CreateRestOfNormalProfiles(), CSimulation::dGetDistanceBetween(), CSimulation::DoCoastCurvature(), CSimulation::dTriangleAreax2(), CSimulation::MarkPolygonCells(), CSimulation::nCalcPotentialPlatformErosionOnProfile(), CSimulation::nCreateAllProfilesAndCheckForIntersection(), CSimulation::nDoAllShadowZones(), CSimulation::nGetCoastNormalEndPoint(), operator!=(), operator=(), operator==(), CSimulation::PtAverage(), CSimulation::PtChooseEndPoint(), CSimulation::PtGetPerpendicular(), CSimulation::PtiExtCRSToGrid(), and CSimulation::RasterizePolygonJoiningLine().
dGetY()
double CGeom2DPoint::dGetY (void) const
Returns the CGeom2DPoint object's double Y co-ordinate.
Definition at line 48 of file 2d_point.cpp.
Referenced by CSimulation::bIsWithinPolygon(), CSimulation::bWriteVectorGISFile(), CSimulation::CalcCoastTangents(), CSimulation::CreateInterventionProfiles(), CSimulation::CreateNaturalCapeNormalProfiles(), CSimulation::CreateRestOfNormalProfiles(), CSimulation::dGetDistanceBetween(), CSimulation::DoCoastCurvature(), CSimulation::dTriangleAreax2(), CSimulation::nCalcPotentialPlatformErosionOnProfile(), CSimulation::nCreateAllProfilesAndCheckForIntersection(), CSimulation::nDoAllShadowZones(), CSimulation::nGetCoastNormalEndPoint(), operator!=(), operator=(), operator==(), CSimulation::PtAverage(), CSimulation::PtChooseEndPoint(), CSimulation::PtGetPerpendicular(), CSimulation::PtiExtCRSToGrid(), and CSimulation::RasterizePolygonJoiningLine().
operator!=()
bool CGeom2DPoint::operator!= (CGeom2DPoint * pPt) const
Compares two CGeom2DPoint objects for inequality.
Definition at line 104 of file 2d_point.cpp.
operator=()
void CGeom2DPoint::operator= (CGeom2DPoint * pPt)
Sets one CGeom2DPoint object equal to another.
Definition at line 79 of file 2d_point.cpp.
operator==() [1/2]
bool CGeom2DPoint::operator== (CGeom2DPoint * pPt) const
Compares two CGeom2DPoint objects for equality.
Definition at line 86 of file 2d_point.cpp.
operator==() [2/2]
bool CGeom2DPoint::operator== (CGeom2DPoint pPt) const
Compares two CGeom2DPoint objects for equality.
Definition at line 95 of file 2d_point.cpp.
SetX()
void CGeom2DPoint::SetX (double const dNewX)
The double parameter sets a value for the CGeom2DIPoint object's X co-ordinate.
Definition at line 54 of file 2d_point.cpp.
Referenced by CSimulation::nCreateProfile(), CSimulation::nDoCliffCollapseDeposition(), CSimulation::nGetCoastNormalEndPoint(), CSimulation::PtChooseEndPoint(), CSimulation::PtGetPerpendicular(), and CSimulation::RasterizeProfile().
SetY()
void CGeom2DPoint::SetY (double const dNewY)
The double parameter sets a value for the CGeom2DIPoint object's Y co-ordinate.
Definition at line 60 of file 2d_point.cpp.
Referenced by CSimulation::nCreateProfile(), CSimulation::nDoCliffCollapseDeposition(), CSimulation::nGetCoastNormalEndPoint(), CSimulation::PtChooseEndPoint(), CSimulation::PtGetPerpendicular(), and CSimulation::RasterizeProfile().
Field Documentation
dX
double CGeom2DPoint::dX private
The x co-ordinate.
Definition at line 33 of file 2d_point.h.
Referenced by dGetX(), operator!=(), operator=(), operator==(), and SetX().
dY
double CGeom2DPoint::dY private
The y co-ordinate.
Definition at line 36 of file 2d_point.h.
Referenced by dGetY(), operator!=(), operator=(), operator==(), and SetY().
The documentation for this class was generated from the following files:
2d_point.h
2d_point.cpp