CoastalME (Coastal Modelling Environment): interpolate.h File Reference
interpolate.h File Reference
Definitions of Linear interpolation routines.
Functions
double dInterpolate (vector< double >, vector< double >, double, bool)
Returns interpolated value at x from parallel arrays (VdXdata, VdYdata). Assumes that VdXdata has at least two elements, is sorted and is strictly monotonically increasing. The boolean argument extrapolate determines behaviour beyond ends of array (if needed). For this version, both lots of data are doubles.
double dInterpolate (vector< int >, vector< double >, int, bool)
Returns interpolated value at x from parallel arrays (VdXdata, VdYdata). Assumes that VdXdata has at least two elements, is sorted and is strictly monotonically increasing. The boolean argument extrapolate determines behaviour beyond ends of array (if needed). For this version, one lot of data is integer and the other is double.
Detailed Description
Definitions of Linear interpolation routines.
TODO A more detailed description of these routines.
Author
http://www.cplusplus.com/forum/general/216928/
Modified by David Favis-Mortlock and Andres Payo
Date
2023
Copyright
GNU Lesser General Public License
Definition in file interpolate.h.
Function Documentation
dInterpolate() [1/2]
double dInterpolate (vector< double > VdXdata, vector< double > VdYdata, double dX, bool bExtrapolate)
Returns interpolated value at x from parallel arrays (VdXdata, VdYdata). Assumes that VdXdata has at least two elements, is sorted and is strictly monotonically increasing. The boolean argument extrapolate determines behaviour beyond ends of array (if needed). For this version, both lots of data are doubles.
Definition at line 34 of file interpolate.cpp.
Referenced by CSimulation::dLookUpErosionPotential(), CSimulation::InterpolateWaveHeightToCoastPoints(), and CSimulation::WriteLookUpData().
dInterpolate() [2/2]
double dInterpolate (vector< int > VnXdata, vector< double > VdYdata, int nX, bool bExtrapolate)
Returns interpolated value at x from parallel arrays (VdXdata, VdYdata). Assumes that VdXdata has at least two elements, is sorted and is strictly monotonically increasing. The boolean argument extrapolate determines behaviour beyond ends of array (if needed). For this version, one lot of data is integer and the other is double.
Definition at line 68 of file interpolate.cpp.