CoastalME (Coastal Modelling Environment): CRWCliff Class Reference
CRWCliff Class Reference
Real-world class used to represent the 'cliff' category of coastal landform object.
#include <cliff.h>
Inherits CACoastLandform.
Public Member Functions
CRWCliff (CRWCoast *, int const, int const, double const, double const, double const, double const)
Constructor with seven parameters and an intialization list.
~CRWCliff (void)
Destructor.
void SetCliffCollapsed (void)
Flags the cliff as having collapsed.
bool bHasCollapsed (void) const
Returns the value of the cliff collapse switch.
void SetNotchBaseElev (double const)
Sets the elevation of the base of the erosional notch.
double dGetNotchBaseElev (void) const
Returns the elevation of the base of the erosional notch.
double dGetRemaining (void) const
Returns the length (in external CRS units) of the cliff's remaining sediment 'behind' the erosional notch.
double dGetNotchDepth (void) const
Returns the horizontal depth of the cliff's erosional notch (the 'overhang')
bool bReadyToCollapse (double const) const
Returns true if the horizontal depth of the erosional notch exceeds the critical notch overhang.
void DeepenErosionalNotch (double const)
Increases the XY-plane length (in external CRS units) of the erosional notch, measured inland from the side of the cell that touches the sea.
void Display (void) override
Instantiates the pure virtual function in the abstract parent class, so that CRWCliff is not an abstract class.
Public Member Functions inherited from CACoastLandform
CACoastLandform (void)
Constructor with initialization list.
virtual ~CACoastLandform (void)
Destructor.
int nGetCoast (void) const
Get the number of the coast on which this coast landform sits.
int nGetPointOnCoast (void) const
Get the point on the coast on which this coast landform sits.
int nGetLandFormCategory (void) const
Get the landform category.
CGeom2DIPoint * pPtiGetCellMarkedAsLF (void) const
Get the grid co-ordinates of the cell on which this coast landform sits.
void IncTotAccumWaveEnergy (double const)
Increment total accumulated wave energy.
double dGetTotAccumWaveEnergy (void) const
Get total accumulated wave energy.
virtual void Display ()=0
Private Attributes
bool m_bCliffHasCollapsed
Switch to say whether the cliff has just collapsed, earlier in this timestep.
double m_dMaxDepth
The maximum depth (in external CRS units) of an erosional notch, this is equal to the grid's m_dCellSide.
double m_dNotchDepth
The horizontal depth (in external CRS units) of the erosional notch, measured inland from the side of the cell that touches the sea.
double m_dNotchBaseElev
Z-plane elevation (in external CRS units) of the base of the erosional notch. The notch is assumed to extend across the whole width of the coast cell, along the side of the cell that touches the sea.
Additional Inherited Members
Protected Attributes inherited from CACoastLandform
int m_nCoast
The coast number on which this coast landform sits.
int m_nPointOnCoast
The point on the coast on which this coast landform sits.
int m_nCategory
Landform category code.
double m_dTotAccumWaveEnergy
Total accumulated wave energy since beginning of simulation.
CRWCoast * pCoast
Pointer to this landform's coast.
Detailed Description
Real-world class used to represent the 'cliff' category of coastal landform object.
TODO This is a more detailed description of the CRWCliff class.
Author
David Favis-Mortlock
Andres Payo
Date
2024
Copyright
GNU General Public License
Definition at line 34 of file cliff.h.
Constructor & Destructor Documentation
CRWCliff()
CRWCliff::CRWCliff (CRWCoast * pCoastIn, int const nCoast, int const nPointOnCoast, double const dCellSide, double const dNotchDepthIn, double const dNotchElevIn, double const dAccumWaveEnergyIn)
Constructor with seven parameters and an intialization list.
Definition at line 36 of file cliff.cpp.
~CRWCliff()
CRWCliff::~CRWCliff (void)
Destructor.
Definition at line 54 of file cliff.cpp.
Member Function Documentation
bHasCollapsed()
bool CRWCliff::bHasCollapsed (void) const
Returns the value of the cliff collapse switch.
Definition at line 59 of file cliff.cpp.
Referenced by CSimulation::nLandformToGrid().
bReadyToCollapse()
bool CRWCliff::bReadyToCollapse (double const dThresholdNotchDepth) const
Returns true if the horizontal depth of the erosional notch exceeds the critical notch overhang.
Definition at line 101 of file cliff.cpp.
Referenced by CSimulation::nDoAllWaveEnergyToCoastLandforms().
DeepenErosionalNotch()
void CRWCliff::DeepenErosionalNotch (double const dLenIn)
Increases the XY-plane length (in external CRS units) of the erosional notch, measured inland from the side of the cell that touches the sea.
Definition at line 110 of file cliff.cpp.
Referenced by CSimulation::nDoAllWaveEnergyToCoastLandforms().
dGetNotchBaseElev()
double CRWCliff::dGetNotchBaseElev (void) const
Returns the elevation of the base of the erosional notch.
Definition at line 71 of file cliff.cpp.
Referenced by CSimulation::nDoCliffCollapse(), and CSimulation::nLandformToGrid().
dGetNotchDepth()
double CRWCliff::dGetNotchDepth (void) const
Returns the horizontal depth of the cliff's erosional notch (the 'overhang')
Definition at line 95 of file cliff.cpp.
Referenced by CSimulation::bWriteVectorGISFile(), and CSimulation::nLandformToGrid().
dGetRemaining()
double CRWCliff::dGetRemaining (void) const
Returns the length (in external CRS units) of the cliff's remaining sediment 'behind' the erosional notch.
Definition at line 83 of file cliff.cpp.
Referenced by CSimulation::nLandformToGrid().
Display()
void CRWCliff::Display (void) override virtual
Instantiates the pure virtual function in the abstract parent class, so that CRWCliff is not an abstract class.
Implements CACoastLandform.
Definition at line 121 of file cliff.cpp.
SetCliffCollapsed()
void CRWCliff::SetCliffCollapsed (void)
Flags the cliff as having collapsed.
Definition at line 65 of file cliff.cpp.
Referenced by CSimulation::nDoCliffCollapse().
SetNotchBaseElev()
void CRWCliff::SetNotchBaseElev (double const dNewElev)
Sets the elevation of the base of the erosional notch.
Definition at line 77 of file cliff.cpp.
Referenced by CSimulation::nDoCliffCollapse().
Field Documentation
m_bCliffHasCollapsed
bool CRWCliff::m_bCliffHasCollapsed private
Switch to say whether the cliff has just collapsed, earlier in this timestep.
Definition at line 38 of file cliff.h.
Referenced by bHasCollapsed(), CRWCliff(), and SetCliffCollapsed().
m_dMaxDepth
double CRWCliff::m_dMaxDepth private
The maximum depth (in external CRS units) of an erosional notch, this is equal to the grid's m_dCellSide.
Definition at line 41 of file cliff.h.
Referenced by CRWCliff(), DeepenErosionalNotch(), and dGetRemaining().
m_dNotchBaseElev
double CRWCliff::m_dNotchBaseElev private
Z-plane elevation (in external CRS units) of the base of the erosional notch. The notch is assumed to extend across the whole width of the coast cell, along the side of the cell that touches the sea.
Definition at line 47 of file cliff.h.
Referenced by CRWCliff(), dGetNotchBaseElev(), and SetNotchBaseElev().
m_dNotchDepth
double CRWCliff::m_dNotchDepth private
The horizontal depth (in external CRS units) of the erosional notch, measured inland from the side of the cell that touches the sea.
Definition at line 44 of file cliff.h.
Referenced by bReadyToCollapse(), CRWCliff(), DeepenErosionalNotch(), dGetNotchDepth(), and dGetRemaining().
The documentation for this class was generated from the following files:
cliff.h
cliff.cpp