CoastalME (Coastal Modelling Environment): CRWCellLandform Class Reference
CRWCellLandform Class Reference
Real-world class used to represent the landform of a cell.
#include <cell_landform.h>
Public Member Functions
CRWCellLandform ()
Constructor.
~CRWCellLandform (void)
Destructor.
void SetLFCategory (int const)
Set the landform category and initialise the sub-category.
int nGetLFCategory (void) const
Get the landform category.
void SetLFSubCategory (int const)
Set the both the landform sub-category, and the landform category.
int nGetLFSubCategory (void) const
Get the landform sub-category.
void SetCoast (int const)
Set the coast number.
int nGetCoast (void) const
Get the coast number.
void SetPointOnCoast (int const)
Set the number of the point on the coastline.
int nGetPointOnCoast (void) const
Set the number of the point on the coastline.
void SetAccumWaveEnergy (double const)
Set accumulated wave energy.
double dGetAccumWaveEnergy (void) const
Get accumulated wave energy.
void SetCliffNotchBaseElev (double const)
Set cliff notch base elevation.
double dGetCliffNotchBaseElev (void) const
Get cliff notch base elevation.
void SetCliffNotchDepth (double const)
Set the cliff notch overhang which remains on this cell.
double dGetCliffNotchDepth (void) const
Get the cliff notch overhang which remains on this cell.
void SetCliffRemaining (double const)
Set the cliff depth remaining on this cell.
double dGetCliffRemaining (void) const
Get the cliff depth remaining on this cell.
Private Attributes
int m_nCategory
Landform category for this cell.
int m_nSubCategory
Landform subcategory for this cell.
int m_nCoast
Coast on which this landform sits (if any)
int m_nPointOnCoast
Point on coast on which this landform sits (if any)
double m_dAccumWaveEnergy
Accumulate wave energy for this landform on this cell.
union {
struct {
int m_nDummy
Currently unused for all landforms except cliffs.
} m_sBeachData
struct {
double m_dNotchBaseElev
Cliff notch base elevation.
double m_dNotchDepth
Cliff notch incised depth.
double m_dRemaining
Cliff notch depth remaining.
} m_sCliffData
} m_uLFData
Detailed Description
Real-world class used to represent the landform of a cell.
TODO This is a more detailed description of the CCRWCellLandform class.
Author
David Favis-Mortlock
Andres Payo
Date
2023
Copyright
GNU General Public License
Definition at line 30 of file cell_landform.h.
Constructor & Destructor Documentation
CRWCellLandform()
CRWCellLandform::CRWCellLandform ()
Constructor.
Definition at line 29 of file cell_landform.cpp.
~CRWCellLandform()
CRWCellLandform::~CRWCellLandform (void)
Destructor.
Definition at line 39 of file cell_landform.cpp.
Member Function Documentation
dGetAccumWaveEnergy()
double CRWCellLandform::dGetAccumWaveEnergy (void) const
Get accumulated wave energy.
Definition at line 105 of file cell_landform.cpp.
Referenced by CSimulation::nAssignAllCoastalLandforms().
dGetCliffNotchBaseElev()
double CRWCellLandform::dGetCliffNotchBaseElev (void) const
Get cliff notch base elevation.
Definition at line 117 of file cell_landform.cpp.
Referenced by CSimulation::nAssignAllCoastalLandforms().
dGetCliffNotchDepth()
double CRWCellLandform::dGetCliffNotchDepth (void) const
Get the cliff notch overhang which remains on this cell.
Definition at line 129 of file cell_landform.cpp.
Referenced by CSimulation::nAssignAllCoastalLandforms().
dGetCliffRemaining()
double CRWCellLandform::dGetCliffRemaining (void) const
Get the cliff depth remaining on this cell.
Definition at line 141 of file cell_landform.cpp.
Referenced by CSimulation::nAssignAllCoastalLandforms().
nGetCoast()
int CRWCellLandform::nGetCoast (void) const
Get the coast number.
Definition at line 81 of file cell_landform.cpp.
Referenced by CSimulation::nDoSedimentInputEvent().
nGetLFCategory()
int CRWCellLandform::nGetLFCategory (void) const
Get the landform category.
Definition at line 51 of file cell_landform.cpp.
Referenced by CSimulation::bWriteRasterGISFile(), CSimulation::GetRasterOutputMinMax(), CSimulation::nAssignAllCoastalLandforms(), CSimulation::nAssignNonCoastlineLandforms(), CSimulation::nDoCliffCollapseDeposition(), CSimulation::nDoParallelProfileUnconsErosion(), CSimulation::nDoUnconsDepositionOnPolygon(), CSimulation::nDoUnconsErosionOnPolygon(), CGeomCell::nGetInterventionClass(), CSimulation::nTraceCoastLine(), and CSimulation::nTraceFloodCoastLine().
nGetLFSubCategory()
int CRWCellLandform::nGetLFSubCategory (void) const
Get the landform sub-category.
Definition at line 69 of file cell_landform.cpp.
Referenced by CSimulation::bWriteRasterGISFile(), CSimulation::GetRasterOutputMinMax(), and CGeomCell::nGetInterventionClass().
nGetPointOnCoast()
int CRWCellLandform::nGetPointOnCoast (void) const
Set the number of the point on the coastline.
Definition at line 93 of file cell_landform.cpp.
Referenced by CSimulation::nDoSedimentInputEvent().
SetAccumWaveEnergy()
void CRWCellLandform::SetAccumWaveEnergy (double const dEnergyIn)
Set accumulated wave energy.
Definition at line 99 of file cell_landform.cpp.
Referenced by CSimulation::nLandformToGrid().
SetCliffNotchBaseElev()
void CRWCellLandform::SetCliffNotchBaseElev (double const dElevIn)
Set cliff notch base elevation.
Definition at line 111 of file cell_landform.cpp.
Referenced by CSimulation::nAssignAllCoastalLandforms(), and CSimulation::nLandformToGrid().
SetCliffNotchDepth()
void CRWCellLandform::SetCliffNotchDepth (double const dLenIn)
Set the cliff notch overhang which remains on this cell.
Definition at line 123 of file cell_landform.cpp.
Referenced by CSimulation::nAssignAllCoastalLandforms(), and CSimulation::nLandformToGrid().
SetCliffRemaining()
void CRWCellLandform::SetCliffRemaining (double const dLenIn)
Set the cliff depth remaining on this cell.
Definition at line 135 of file cell_landform.cpp.
Referenced by CSimulation::nAssignAllCoastalLandforms(), and CSimulation::nLandformToGrid().
SetCoast()
void CRWCellLandform::SetCoast (int const nCoastIn)
Set the coast number.
Definition at line 75 of file cell_landform.cpp.
Referenced by CSimulation::nAssignAllCoastalLandforms().
SetLFCategory()
void CRWCellLandform::SetLFCategory (int const nClassIn)
Set the landform category and initialise the sub-category.
Definition at line 44 of file cell_landform.cpp.
Referenced by CGeomCell::CGeomCell(), CSimulation::FloodFillSea(), CSimulation::nAssignNonCoastlineLandforms(), CSimulation::nReadRasterGISFile(), and CGeomCell::SetInterventionClass().
SetLFSubCategory()
void CRWCellLandform::SetLFSubCategory (int const nClassIn)
Set the both the landform sub-category, and the landform category.
Definition at line 57 of file cell_landform.cpp.
Referenced by CSimulation::nAssignAllCoastalLandforms(), CSimulation::nAssignNonCoastlineLandforms(), CSimulation::nDoCliffCollapseDeposition(), CSimulation::nDoParallelProfileUnconsErosion(), CSimulation::nDoUnconsDepositionOnPolygon(), CSimulation::nLandformToGrid(), and CGeomCell::SetInterventionClass().
SetPointOnCoast()
void CRWCellLandform::SetPointOnCoast (int const nPointOnCoastIn)
Set the number of the point on the coastline.
Definition at line 87 of file cell_landform.cpp.
Referenced by CSimulation::nAssignAllCoastalLandforms().
Field Documentation
m_dAccumWaveEnergy
double CRWCellLandform::m_dAccumWaveEnergy private
Accumulate wave energy for this landform on this cell.
Definition at line 46 of file cell_landform.h.
Referenced by dGetAccumWaveEnergy(), and SetAccumWaveEnergy().
m_dNotchBaseElev
double CRWCellLandform::m_dNotchBaseElev
Cliff notch base elevation.
Definition at line 60 of file cell_landform.h.
m_dNotchDepth
double CRWCellLandform::m_dNotchDepth
Cliff notch incised depth.
Definition at line 63 of file cell_landform.h.
m_dRemaining
double CRWCellLandform::m_dRemaining
Cliff notch depth remaining.
Definition at line 66 of file cell_landform.h.
m_nCategory
int CRWCellLandform::m_nCategory private
Landform category for this cell.
Definition at line 34 of file cell_landform.h.
Referenced by nGetLFCategory(), SetLFCategory(), and SetLFSubCategory().
m_nCoast
int CRWCellLandform::m_nCoast private
Coast on which this landform sits (if any)
Definition at line 40 of file cell_landform.h.
Referenced by nGetCoast(), and SetCoast().
m_nDummy
int CRWCellLandform::m_nDummy
Currently unused for all landforms except cliffs.
Definition at line 53 of file cell_landform.h.
m_nPointOnCoast
int CRWCellLandform::m_nPointOnCoast private
Point on coast on which this landform sits (if any)
Definition at line 43 of file cell_landform.h.
Referenced by nGetPointOnCoast(), and SetPointOnCoast().
m_nSubCategory
int CRWCellLandform::m_nSubCategory private
Landform subcategory for this cell.
Definition at line 37 of file cell_landform.h.
Referenced by nGetLFSubCategory(), SetLFCategory(), and SetLFSubCategory().
struct { ... } CRWCellLandform::m_sBeachData
struct { ... } CRWCellLandform::m_sCliffData
union { ... } CRWCellLandform::m_uLFData
Referenced by dGetCliffNotchBaseElev(), dGetCliffNotchDepth(), dGetCliffRemaining(), SetCliffNotchBaseElev(), SetCliffNotchDepth(), and SetCliffRemaining().
The documentation for this class was generated from the following files:
cell_landform.h
cell_landform.cpp